Models/Nationality.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FifaStore.Models
{
    public class Nationality
    {
        public int ID { get; set; }
        [Display(Name = "Nazwa kraju"), Required, StringLength(50, MinimumLength = 2)]
        public string Name { get; set; }
        [Display(Name = "Skrót nazwy"), Required, StringLength(3, MinimumLength = 2)]
        public string Short { get; set; }
        [Display(Name = "Flaga")]
        public string Flag { get; set; }
        public virtual ICollection<Footballer> Footballers { get; set; }
    }
}

Controllers/NationalitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FifaStore.DAL;
using FifaStore.Models;
using PagedList;

namespace FifaStore.Controllers
{
    public class NationalitiesController : Controller
    {
        private FSContext db = new FSContext();

        // GET: Nationalities
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.ShortSortParm = String.IsNullOrEmpty(sortOrder) ? "short_desc" : "short_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var nationalities = from n in db.Nationalities select n;

            if (!String.IsNullOrEmpty(searchString))
            {
                nationalities = nationalities.Where(n => n.Name.Contains(searchString) || n.Short.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    nationalities = nationalities.OrderByDescending(n => n.Name);
                    break;
                case "short_asc":
                    nationalities = nationalities.OrderBy(n => n.Short);
                    break;
                case "short_desc":
                    nationalities = nationalities.OrderByDescending(n => n.Short);
                    break;
                default:
                    nationalities = nationalities.OrderBy(n => n.Name);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(nationalities.ToPagedList(pageNumber, pageSize));
        }

        // GET: Nationalities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nationality nationality = db.Nationalities.Find(id);
            if (nationality == null)
            {
                return HttpNotFound();
            }
            return View(nationality);
        }

        // GET: Nationalities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Nationalities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Short,Flag")] Nationality nationality, HttpPostedFileBase files)
        {
            if (ModelState.IsValid && files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/NationalityFlags/"), fileName);
                files.SaveAs(path);
                nationality.Flag = "NationalityFlags/" + fileName;

                db.Nationalities.Add(nationality);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nationality);
        }

        // GET: Nationalities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nationality nationality = db.Nationalities.Find(id);
            if (nationality == null)
            {
                return HttpNotFound();
            }
            return View(nationality);
        }

        // POST: Nationalities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Short,Flag")] Nationality nationality, HttpPostedFileBase files)
        {
            if (ModelState.IsValid)
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/NationalityFlags/"), fileName);
                    files.SaveAs(path);
                    nationality.Flag = "NationalityFlags/" + fileName;
                }

                db.Entry(nationality).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nationality);
        }

        // GET: Nationalities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nationality nationality = db.Nationalities.Find(id);
            if (nationality == null)
            {
                return HttpNotFound();
            }
            return View(nationality);
        }

        // POST: Nationalities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nationality nationality = db.Nationalities.Find(id);
            db.Nationalities.Remove(nationality);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Nationalities/Create.cshtml
@model FifaStore.Models.Nationality

@{
    ViewBag.Title = "Narodowości";
}

<h2>Utwórz narodowość</h2>


@using (Html.BeginForm("Create", "Nationalities", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>
	<a href="~/Views/Nationalities/Create.cshtml">~/Views/Nationalities/Create.cshtml</a>
	<a href="~/Views/Nationalities/Delete.cshtml">~/Views/Nationalities/Delete.cshtml</a>
	<a href="~/Views/Nationalities/Details.cshtml">~/Views/Nationalities/Details.cshtml</a>
	<a href="~/Views/Nationalities/Edit.cshtml">~/Views/Nationalities/Edit.cshtml</a>
	<a href="~/Views/Nationalities/Index.cshtml">~/Views/Nationalities/Index.cshtml</a>

	<div class="form-group">
		@Html.LabelFor(model => model.Short, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Short, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Short, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Flag, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			<input type="file" name="files" />
			@Html.ValidationMessageFor(model => model.Flag, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Utwórz" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Nationalities/Delete.cshtml
@model FifaStore.Models.Nationality

@{
	ViewBag.Title = "Narodowości - usuwanie";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć następujący element?</h3>
<div>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Short)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Short)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Flag)
		</dt>

		<dd>
			<img src="~/Images/@Model.Flag" alt="@Model.Flag" height="50px" width="72px" />
		</dd>

	</dl>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Usuń" class="btn btn-default" /> |
			@Html.ActionLink("Powrót do listy", "Index")
		</div>
	}
</div>

Views/Nationalities/Details.cshtml
@model FifaStore.Models.Nationality

@{
    ViewBag.Title = "Details";
}

<img src="~/Images/@Model.Flag" alt="@Model.Flag" height="150px" width="216px" />

<div>
    <h4>Narodowość</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Short)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Short)
        </dd>

    </dl>
</div>
<p>
	@if (Context.User.IsInRole("Moderator"))
	{
		@Html.ActionLink("Edytuj", "Edit", new { id = Model.ID })
		@:|
	}
	@Html.ActionLink("Powrót do listy", "Index")
</p>

Views/Nationalities/Edit.cshtml
@model FifaStore.Models.Nationality

@{
    ViewBag.Title = "Narodowości - edycja";
}

<h2>Edytuj</h2>

@using (Html.BeginForm("Edit", "Nationalities", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Short, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Short, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Short, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" />
                @Html.ValidationMessageFor(model => model.Flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Nationalities/Index.cshtml
@model PagedList.IPagedList<FifaStore.Models.Nationality>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
	ViewBag.Title = "Narodowości";
}

<h2>Narodowości</h2>

@if (Context.User.IsInRole("Moderator"))
{
	<p>
		@Html.ActionLink("Dodaj narodowość", "Create")
	</p>
}

@using (Html.BeginForm("Index", "Nationalities", FormMethod.Get))
{
	<p>
		Szukaj po frazie: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
		<input type="submit" value="Szukaj" />
	</p>
}
<table class="table">
	<tr>
		<th>
			Flaga
		</th>
		<th>
			@Html.ActionLink("Nazwa", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
		</th>
		<th>
			@Html.ActionLink("Skrót", "Index", new { sortOrder = ViewBag.ShortSortParm, currentFilter = ViewBag.CurrentFilter })
		</th>
		@if (Context.User.IsInRole("Moderator"))
		{
			<th></th>
		}
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				<a href="/Nationalities/Details?id=@item.ID">
					<img src="~/Images/@item.Flag" alt="@item.Flag" height="50px" width="84px" />
				</a>
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Name)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Short)
			</td>

			@if (Context.User.IsInRole("Moderator"))
			{
				<td>
					@Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
					@Html.ActionLink("Usuń", "Delete", new { id = item.ID })
				</td>
			}
		</tr>
	}
</table>

<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
	new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))