Models/Footballer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FifaStore.Models
{
    public class Footballer
    {
        public int ID { get; set; }
        [Display(Name = "Imię"), Required, StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }
        [Display(Name = "Nazwisko"), Required, StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }
        [Display(Name = "Przydomek")]
        public string Alias { get; set; }
        [Display(Name = "Narodowość"), Required]
        public int NationalityID { get; set; }
        [Display(Name = "Klub"), Required]
        public int ClubID { get; set; }
        [Display(Name = "Zdjęcie zawodnika")]
        public string Photo { get; set; }
        public virtual Club Club { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}

Controllers/FootballersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FifaStore.DAL;
using FifaStore.Models;
using PagedList;

namespace FifaStore.Controllers
{
    public class FootballersController : Controller
    {
        private FSContext db = new FSContext();

        // GET: Footballers
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, string nationSortParm, string leagueSortParm, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lastName_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.LeagueSortParm = leagueSortParm;
            ViewBag.NationSortParm = nationSortParm;

            var footballers = from l in db.Footballers select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                footballers = footballers.Where(l => l.FirstName.Contains(searchString) || l.LastName.Contains(searchString) || l.Alias.Contains(searchString)).Include(f => f.Nationality);
            }
            if (!String.IsNullOrEmpty(nationSortParm))
            {
                int nationID = int.Parse(nationSortParm);
                footballers = footballers.Where(f => f.NationalityID == nationID).Include(f => f.Club).Include(f => f.Nationality);
            }
            if (!String.IsNullOrEmpty(leagueSortParm))
            {
                int leagueID = int.Parse(leagueSortParm);
                footballers = footballers.Where(f => f.Club.LeagueID == leagueID).Include(f => f.Club).Include(f => f.Nationality);
            }
            switch (sortOrder)
            {
                case "lastName_desc":
                    footballers = footballers.OrderByDescending(l => l.LastName).Include(f => f.Club).Include(f => f.Nationality);
                    break;
                default:
                    footballers = footballers.OrderBy(l => l.LastName).Include(f => f.Club).Include(f => f.Nationality);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var nations = from n in db.Nationalities select n;
            ViewBag.Nations = nations.ToList();
            var leagues = from l in db.Leagues select l;
            ViewBag.Leagues = leagues.ToList();

            return View(footballers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Footballers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Footballer footballer = db.Footballers.Find(id);
            if (footballer == null)
            {
                return HttpNotFound();
            }
            return View(footballer);
        }

        // GET: Footballers/Create
        public ActionResult Create()
        {
            ViewBag.ClubID = new SelectList(db.Clubs, "ID", "Name");
            ViewBag.NationalityID = new SelectList(db.Nationalities, "ID", "Name");
            return View();
        }

        // POST: Footballers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Alias,NationalityID,ClubID,Photo")] Footballer footballer, HttpPostedFileBase files)
        {
            if (ModelState.IsValid && files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/FootballerPortraits/"), fileName);
                files.SaveAs(path);
                footballer.Photo = "FootballerPortraits/" + fileName;

                db.Footballers.Add(footballer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClubID = new SelectList(db.Clubs, "ID", "Name", footballer.ClubID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "ID", "Name", footballer.NationalityID);
            return View(footballer);
        }

        // GET: Footballers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Footballer footballer = db.Footballers.Find(id);
            if (footballer == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClubID = new SelectList(db.Clubs, "ID", "Name", footballer.ClubID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "ID", "Name", footballer.NationalityID);
            return View(footballer);
        }

        // POST: Footballers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,Alias,NationalityID,ClubID,Photo")] Footballer footballer, HttpPostedFileBase files)
        {
            if (ModelState.IsValid)
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/FootballerPortraits/"), fileName);
                    files.SaveAs(path);
                    footballer.Photo = "FootballerPortraits/" + fileName;
                }

                db.Entry(footballer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClubID = new SelectList(db.Clubs, "ID", "Name", footballer.ClubID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "ID", "Name", footballer.NationalityID);
            return View(footballer);
        }

        // GET: Footballers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Footballer footballer = db.Footballers.Find(id);
            if (footballer == null)
            {
                return HttpNotFound();
            }
            return View(footballer);
        }

        // POST: Footballers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Footballer footballer = db.Footballers.Find(id);
            db.Footballers.Remove(footballer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Footballers/Create.cshtml
@model FifaStore.Models.Footballer

@{
    ViewBag.Title = "Create";
}

<h2>Utwórz piłkarza</h2>


@using (Html.BeginForm("Create", "Footballers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalityID, "NationalityID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NationalityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NationalityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubID, "ClubID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Footballers/Delete.cshtml
@model FifaStore.Models.Footballer

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć następujący element?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Club.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club.Name)
            <img src="~/Images/@Model.Club.ClubCrest" alt="@Model.Club.ClubCrest" height="50px" width="50px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality.Name)
            <img src="~/Images/@Model.Nationality.Flag" alt="@Model.Nationality.Flag" height="50px" width="72px" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy", "Index")
        </div>
    }
</div>

Views/Footballers/Details.cshtml
@model FifaStore.Models.Footballer

@{
    ViewBag.Title = "Details";
}

<img src="~/Images/@Model.Photo" alt="@Model.Photo" height="150px" width="150px" />

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            <img src="~/Images/@Model.Club.ClubCrest" alt="@Model.Club.ClubCrest" height="50px" width="50px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club.Name)
        </dd>

        <dt>
            <img src="~/Images/@Model.Nationality.Flag" alt="@Model.Nationality.Flag" height="50px" width="72px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality.Name)
        </dd>

    </dl>
</div>
<p>
    @if (Context.User.IsInRole("Moderator"))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID })
        @:|
    }
    @Html.ActionLink("Powrót do listy", "Index")
</p>

Views/Footballers/Edit.cshtml
@model FifaStore.Models.Footballer

@{
    ViewBag.Title = "Piłkarze edycja";
}

<h2>Edytuj</h2>


@using (Html.BeginForm("Edit", "Footballers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalityID, "NationalityID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NationalityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NationalityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubID, "ClubID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Footballers/Index.cshtml
@model PagedList.IPagedList<FifaStore.Models.Footballer>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Piłkarze";
}

<h2>Piłkarze</h2>

@if (Context.User.IsInRole("Moderator"))
{
    <p>
        @Html.ActionLink("Dodaj piłkarza", "Create")
    </p>
}

@using (Html.BeginForm("Index", "Footballers", FormMethod.Get))
{
    <p>
        Szukaj po frazie: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        @Html.DropDownList("NationSortParm", new SelectList(ViewBag.Nations, "ID", "Name"), "Narodowość")
        @Html.DropDownList("LeagueSortParm", new SelectList(ViewBag.Leagues, "ID", "Name"), "Liga")
        <input type="submit" value="Szukaj" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Zdjęcie
        </th>
        <th>
            @Html.ActionLink("Imię, nazwisko, alias", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter, leagueSortParm = ViewBag.LeagueSortParm, nationSortParm = ViewBag.NationSortParm })
        </th>
        <th>
            Narodowość
        </th>
        <th>
            Klub
        </th>
        @if (Context.User.IsInRole("Moderator"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="/Footballers/Details?id=@item.ID">
                    <img src="~/Images/@item.Photo" alt="@item.Photo" height="50px" width="50px" />
                </a>
            </td>
            <td>
                @if (item.Alias != " ")
                {
                    @item.FirstName
                    @:
                    @item.LastName
                }
                else
                {
                    @item.FirstName
                    @:
                    @item.LastName
                    @: "
                    @item.Alias
                    @:"
                }
            </td>
            <td>
                <img src="~/Images/@item.Nationality.Flag" alt="@item.Nationality.Flag" height="50px" width="72px" />
            </td>
            <td>
                <img src="~/Images/@item.Club.ClubCrest" alt="@item.Club.ClubCrest" height="50px" width="50px" />
            </td>
            @if (Context.User.IsInRole("Moderator"))
            {
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }
</table>

<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))