Controllers/CardTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FifaStore.DAL;
using FifaStore.Models;
using PagedList;

namespace FifaStore.Controllers
{
    public class CardTypesController : Controller
    {
        private FSContext db = new FSContext();

        // GET: CardTypes
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var cardTypes = from l in db.CardTypes select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                cardTypes = cardTypes.Where(l => l.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    cardTypes = cardTypes.OrderByDescending(l => l.Name);
                    break;
                default:
                    cardTypes = cardTypes.OrderBy(l => l.Name);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(cardTypes.ToPagedList(pageNumber, pageSize));
        }

        // GET: CardTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardType cardType = db.CardTypes.Find(id);
            if (cardType == null)
            {
                return HttpNotFound();
            }
            return View(cardType);
        }

        // GET: CardTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CardTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,CardBorder")] CardType cardType, HttpPostedFileBase files)
        {
            if (ModelState.IsValid && files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/CardBorders/"), fileName);
                files.SaveAs(path);
                cardType.CardBorder = "CardBorders/" + fileName;

                db.CardTypes.Add(cardType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cardType);
        }

        // GET: CardTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardType cardType = db.CardTypes.Find(id);
            if (cardType == null)
            {
                return HttpNotFound();
            }
            return View(cardType);
        }

        // POST: CardTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,CardBorder")] CardType cardType, HttpPostedFileBase files)
        {
            if (ModelState.IsValid)
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/CardBorders/"), fileName);
                    files.SaveAs(path);
                    cardType.CardBorder = "CardBorders/" + fileName;
                }

                db.Entry(cardType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cardType);
        }

        // GET: CardTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardType cardType = db.CardTypes.Find(id);
            if (cardType == null)
            {
                return HttpNotFound();
            }
            return View(cardType);
        }

        // POST: CardTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CardType cardType = db.CardTypes.Find(id);
            db.CardTypes.Remove(cardType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FifaStore.DAL;
using FifaStore.Models;
using PagedList;

namespace FifaStore.Controllers
{
    public class ClubsController : Controller
    {
        private FSContext db = new FSContext();

        // GET: Clubs
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.ShortSortParm = sortOrder=="Short" ? "short_desc" : "Short";
            ViewBag.LeagueSortParm = sortOrder=="League" ? "league_desc" : "League";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var clubs = from l in db.Clubs select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                clubs = clubs.Where(l => l.Name.Contains(searchString) || l.Short.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    clubs = clubs.OrderByDescending(l => l.Name);
                    break;
                case "Short":
                    clubs = clubs.OrderBy(l => l.Short);
                    break;
                case "short_desc":
                    clubs = clubs.OrderByDescending(l => l.Short);
                    break;
                case "League":
                    clubs = clubs.OrderBy(l => l.League.Short);
                    break;
                case "league_desc":
                    clubs = clubs.OrderByDescending(l => l.League.Short);
                    break;
                default:
                    clubs = clubs.OrderBy(l => l.Name);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(clubs.ToPagedList(pageNumber, pageSize));
        }

        // GET: Clubs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // GET: Clubs/Create
        public ActionResult Create()
        {
            ViewBag.LeagueID = new SelectList(db.Leagues, "ID", "Name");
            return View();
        }

        // POST: Clubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Short,ClubCrest,LeagueID")] Club club, HttpPostedFileBase files)
        {
            if (ModelState.IsValid && files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/ClubCrests/"), fileName);
                files.SaveAs(path);
                club.ClubCrest = "ClubCrests/" + fileName;

                db.Clubs.Add(club);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeagueID = new SelectList(db.Leagues, "ID", "Name", club.LeagueID);
            return View(club);
        }

        // GET: Clubs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "ID", "Name", club.LeagueID);
            return View(club);
        }

        // POST: Clubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Short,ClubCrest,LeagueID")] Club club, HttpPostedFileBase files)
        {
            if (ModelState.IsValid)
            {
                if (files != null && files.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/ClubCrests/"), fileName);
                    files.SaveAs(path);
                    club.ClubCrest = "ClubCrests/" + fileName;
                }

                db.Entry(club).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "ID", "Name", club.LeagueID);
            return View(club);
        }

        // GET: Clubs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // POST: Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Club club = db.Clubs.Find(id);
            db.Clubs.Remove(club);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CardTypes/Create.cshtml
@model FifaStore.Models.CardType

@{
    ViewBag.Title = "Typ karty - utwórz";
}

<h2>Utwórz typ</h2>


@using (Html.BeginForm("Create", "Clubs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CardType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardBorder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" />
                @Html.ValidationMessageFor(model => model.CardBorder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CardTypes/Delete.cshtml
@model FifaStore.Models.CardType

@{
    ViewBag.Title = "Typ karty - usuwanie";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć następujący element?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardBorder)
        </dt>

        <dd>
            <img src="~/Images/@Model.CardBorder" alt="@Model.CardBorder" height="50px" width="36px" />
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy", "Index")
        </div>
    }
</div>

Views/CardTypes/Details.cshtml
@model FifaStore.Models.CardType

@{
    ViewBag.Title = "Typ - karty szczegóły";
}

<img src="~/Images/@Model.CardBorder" alt="@Model.CardBorder" height="150px" width="72px" />

<div>
    <h4>Typ karty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @if (Context.User.IsInRole("Moderator"))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID })
        @:|
    }
    @Html.ActionLink("Powrót do listy", "Index")
</p>

Views/CardTypes/Edit.cshtml
@model FifaStore.Models.CardType

@{
    ViewBag.Title = "Typ karty - edycja";
}

<h2>Edytuj</h2>


@using (Html.BeginForm("Edit", "CardTypes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardBorder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" />
                @Html.ValidationMessageFor(model => model.CardBorder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CardTypes/Index.cshtml
@model PagedList.IPagedList<FifaStore.Models.CardType>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Typy kart";
}

<h2>Typy kart</h2>

@if (Context.User.IsInRole("Moderator"))
{
    <p>
        @Html.ActionLink("Dodaj typ", "Create")
    </p>
}

@using (Html.BeginForm("Index", "CardTypes", FormMethod.Get))
{
    <p>
        Szukaj po frazie: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Ramka
        </th>
        <th>
            @Html.ActionLink("Nazwa", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        @if (Context.User.IsInRole("Moderator"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="/Clubs/Details?id=@item.ID">
                    <img src="~/Images/@item.CardBorder" alt="@item.CardBorder" height="50px" width="36px" />
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @if (Context.User.IsInRole("Moderator"))
            {
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }

</table>

<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))