Models/Card.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FifaStore.Models
{
    public class Card
    {
        public int ID { get; set; }
        public int FootballerID { get; set; }
        public int CardTypeID { get; set; }
        //public List<int> AvaragePrices = new List<int>();
        private int avaragePriceCounter = 0;
        public int AvaragePriceCounter
        {
            get { return avaragePriceCounter; }
            set { avaragePriceCounter = value; }
        }
        private int fullPrice = 0;

        public int FullPrice
        {
            get { return fullPrice; }
            set { fullPrice = value; }
        }
        private float avaragePrice = 0;
        public float AvaragePrice
        {
            get {
                if(avaragePriceCounter != 0)
                {
                    return fullPrice / avaragePriceCounter;
                }
                else
                {
                    return 0;
                }
            }
            set { avaragePrice = value; }
        }
        private int rateCounter = 0;
        public int RateCounter
        {
            get { return rateCounter; }
            set { rateCounter = value; }
        }
        private int fullRate = 0;
        public int FullRate
        {
            get { return fullRate; }
            set { fullRate = value; }
        }
        private float avarageRate = 0;
        public float AvarageRate
        {
            get
            {
                if (rateCounter != 0)
                {
                    return fullRate / rateCounter;
                }
                else
                {
                    return 0;
                }
            }
            set { avarageRate = value; }
        }
        [Required]
        public Position Position { get; set; }
        [Required, Range(1, 99)]
        public int Overall { get; set; }
        [Required, Range(1, 99)]
        public int Pace { get; set; }
        [Required, Range(1, 99)]
        public int Shooting { get; set; }
        [Required, Range(1, 99)]
        public int Passing { get; set; }
        [Required, Range(1, 99)]
        public int Dribbling { get; set; }
        [Required, Range(1, 99)]
        public int Defending { get; set; }
        [Required, Range(1, 99)]
        public int Physicality { get; set; }
        public virtual Footballer Footballer { get; set; }
        public virtual CardType CardType { get; set; }
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual ICollection<Profile> Likers { get; set; }
        public virtual ICollection<Profile> Owners { get; set; }
    }

    public enum Position
    {
        BR,
        CPS, PO, ŚO, LO, CLS,
        PP, PS, PN, LP, LS, LN,
        ŚPD, ŚP, ŚPO, ŚN, N
    }
}

Models/CardType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FifaStore.Models
{
    public class CardType
    {
        public int ID { get; set; }
        [Display(Name = "Nazwa"), Required, StringLength(50, MinimumLength = 1)]
        public string Name { get; set; }
        [Display(Name = "Ramka"), Required]
        public string CardBorder { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}

Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FifaStore.DAL;
using FifaStore.Models;
using PagedList;

namespace FifaStore.Controllers
{
    public class CardsController : Controller
    {
        private FSContext db = new FSContext();

        // GET: Cards
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, string nationSortParm, string leagueSortParm, string cardTypeSortParm, string positionSortParm, string priceMin, string priceMax, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lastName_desc" : "";
            ViewBag.OverallSortParm = sortOrder == "Overall" ? "overall_desc" : "Overall";
            ViewBag.AvaragePriceSortParm = sortOrder == "AvaragePrice" ? "avaragePrice_desc" : "AvaragePrice";
            ViewBag.RateSortParm = sortOrder == "Rate" ? "rate_desc" : "Rate";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.LeagueSortParm = leagueSortParm;
            ViewBag.NationSortParm = nationSortParm;
            ViewBag.CardTypeSortParm = cardTypeSortParm;
            ViewBag.PositionSortParm = positionSortParm;
            ViewBag.PriceMin = priceMin;
            ViewBag.PriceMax = priceMax;

            var cards = from c in db.Cards select c;
            if (!String.IsNullOrEmpty(searchString))
            {
                cards = cards.Where(l => l.Footballer.FirstName.Contains(searchString) || l.Footballer.LastName.Contains(searchString) || l.Footballer.Alias.Contains(searchString)).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(nationSortParm))
            {
                int nationID = int.Parse(nationSortParm);
                cards = cards.Where(f => f.Footballer.NationalityID == nationID).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(leagueSortParm))
            {
                int leagueID = int.Parse(leagueSortParm);
                cards = cards.Where(f => f.Footballer.Club.LeagueID == leagueID).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(cardTypeSortParm))
            {
                int cardTypeID = int.Parse(cardTypeSortParm);
                cards = cards.Where(f => f.CardTypeID == cardTypeID).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(positionSortParm))
            {
                cards = cards.Where(f => f.Position.ToString() == positionSortParm).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(priceMin))
            {
                int min = int.Parse(priceMin);
                cards = cards.Where(f => f.AvaragePrice >= min).Include(c => c.CardType).Include(c => c.Footballer);
            }
            if (!String.IsNullOrEmpty(priceMax))
            {
                int max = int.Parse(priceMax);
                cards = cards.Where(f => f.AvaragePrice <= max).Include(c => c.CardType).Include(c => c.Footballer);
            }

            switch (sortOrder)
            {
                case "lastName_desc":
                    cards = cards.OrderByDescending(l => l.Footballer.LastName);
                    break;
                case "Overall":
                    cards = cards.OrderBy(l => l.Overall);
                    break;
                case "overall_desc":
                    cards = cards.OrderByDescending(l => l.Overall);
                    break;
                case "AvaragePrice":
                    cards = cards.OrderBy(l => l.AvaragePrice);
                    break;
                case "avaragePrice_desc":
                    cards = cards.OrderByDescending(l => l.AvaragePrice);
                    break;
                case "Rate":
                    cards = cards.OrderBy(l => l.AvarageRate);
                    break;
                case "rate_desc":
                    cards = cards.OrderByDescending(l => l.AvarageRate);
                    break;
                default:
                    cards = cards.OrderBy(l => l.Footballer.LastName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var nations = from n in db.Nationalities select n;
            ViewBag.Nations = nations.ToList();
            var leagues = from l in db.Leagues select l;
            ViewBag.Leagues = leagues.ToList();
            var cardTypes = from c in db.CardTypes select c;
            ViewBag.CardTypes = cardTypes.ToList();
            var positions = Enum.GetValues(typeof(Position));
            ViewBag.Positions = positions;

            return View(cards.ToPagedList(pageNumber, pageSize));
        }

        // GET: PrettyCards
        public ActionResult PrettyCards()
        {
            var cards = from c in db.Cards orderby c.Footballer.LastName select c;
            return View(cards);
        }

        // GET: Cards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }

            ViewBag.IsLiked = false;
            ViewBag.IsOwned = false;
            if (User.Identity.IsAuthenticated)
            {
                Profile profile = db.Profiles.Single(p => p.Username == User.Identity.Name);

                if (profile.Owned.Contains(card))
                {
                    ViewBag.IsOwned = true;
                }

                if (profile.Liked.Contains(card))
                {
                    ViewBag.IsLiked = true;
                }
            }

            if(card.Opinions.Count == 0)
            {
                ViewBag.IsComment = false;
            }
            else
            {
                ViewBag.IsComment = true;
                ViewBag.Comments = card.Opinions.ToList();
            }

            return View(card);
        }

        // GET: Cards/Create
        public ActionResult Create()
        {
            ViewBag.CardTypeID = new SelectList(db.CardTypes, "ID", "Name");
            ViewBag.FootballerID = new SelectList(db.Footballers, "ID", "FirstName");
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FootballerID,CardTypeID,AvaragePrice,Rate,Position,Overall,Pace,Shooting,Passing,Dribbling,Defending,Physicality")] Card card)
        {
            if (ModelState.IsValid)
            {
                db.Cards.Add(card);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CardTypeID = new SelectList(db.CardTypes, "ID", "Name", card.CardTypeID);
            ViewBag.FootballerID = new SelectList(db.Footballers, "ID", "FirstName", card.FootballerID);
            return View(card);
        }

        // GET: Cards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardTypeID = new SelectList(db.CardTypes, "ID", "Name", card.CardTypeID);
            ViewBag.FootballerID = new SelectList(db.Footballers, "ID", "FirstName", card.FootballerID);
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FootballerID,CardTypeID,AvaragePrice,Rate,Position,AddDate,Overall,Pace,Shooting,Passing,Dribbling,Defending,Physicality")] Card card)
        {
            if (ModelState.IsValid)
            {
                db.Entry(card).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CardTypeID = new SelectList(db.CardTypes, "ID", "Name", card.CardTypeID);
            ViewBag.FootballerID = new SelectList(db.Footballers, "ID", "FirstName", card.FootballerID);
            return View(card);
        }

        // GET: Cards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Card card = db.Cards.Find(id);
            db.Cards.Remove(card);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

Views/Cards/Details.cshtml
@model FifaStore.Models.Card
@using Newtonsoft.Json


@{
    ViewBag.Title = "Details";
}
<body onload="myCanvas()">
    <canvas id="myCanvas" width="322px" height="450px"></canvas>
</body>

<script type="text/javascript">
    var cardBorder = new Image();
    var playerPhoto = new Image();

    var nationFlag = new Image();
    var clubCrest = new Image();
    var overall = @Html.Raw(JsonConvert.SerializeObject(this.Model.Overall));
    var position = @Html.Raw(JsonConvert.SerializeObject(this.Model.Position.ToString()));

    var lastName = @Html.Raw(JsonConvert.SerializeObject(this.Model.Footballer.LastName.ToUpper()));
    var pac = @Html.Raw(JsonConvert.SerializeObject(this.Model.Pace));
    var sho = @Html.Raw(JsonConvert.SerializeObject(this.Model.Shooting));
    var pas = @Html.Raw(JsonConvert.SerializeObject(this.Model.Passing));
    var dri = @Html.Raw(JsonConvert.SerializeObject(this.Model.Dribbling));
    var def = @Html.Raw(JsonConvert.SerializeObject(this.Model.Defending));
    var phy = @Html.Raw(JsonConvert.SerializeObject(this.Model.Physicality));

    cardBorder.src = "/Images/" + @Html.Raw(JsonConvert.SerializeObject(this.Model.CardType.CardBorder));
    nationFlag.src = "/Images/" + @Html.Raw(JsonConvert.SerializeObject(this.Model.Footballer.Nationality.Flag));
    clubCrest.src = "/Images/" + @Html.Raw(JsonConvert.SerializeObject(this.Model.Footballer.Club.ClubCrest));
    playerPhoto.src = "/Images/" + @Html.Raw(JsonConvert.SerializeObject(this.Model.Footballer.Photo));

    function myCanvas() {

        var ctx = document.getElementById('myCanvas').getContext('2d');

        //from base
        ctx.drawImage(cardBorder, 0, 0, 322, 450);
        ctx.drawImage(nationFlag, 70, 137, 42, 26);
        ctx.drawImage(clubCrest, 71, 177, 40, 40);
        ctx.drawImage(playerPhoto, 80, 35, 200, 200);

        //left panel
        ctx.textAlign = "center";
        ctx.font = "500 50px Arial";
        ctx.fillText(overall, 90, 100, 40);
        ctx.font = "lighter 25px Arial";
        ctx.fillText(position, 90, 125);

        //line under position
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(76, 130);
        ctx.lineTo(106, 130);
        ctx.stroke();

        //line under flag
        ctx.beginPath();
        ctx.moveTo(76, 170);
        ctx.lineTo(106, 170);
        ctx.stroke();

        //bottom panel
        //line under name
        ctx.beginPath();
        ctx.moveTo(70, 277);
        ctx.lineTo(252, 277);
        ctx.stroke();

        //vertical line
        ctx.beginPath();
        ctx.moveTo(150, 373);
        ctx.lineTo(172, 373);
        ctx.stroke();

        //bottom line
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(161, 290);
        ctx.lineTo(161, 362);
        ctx.stroke();

        //name
        ctx.font = "600 33px Arial";
        ctx.fillText(lastName, 161, 268, 180);

        ctx.font = "600 26px Arial";
        //left skills
        ctx.fillText(pac, 90, 305, 20);
        ctx.fillText(sho, 90, 330, 20);
        ctx.fillText(pas, 90, 355, 20);

        //right skills
        ctx.fillText(dri, 200, 305, 20);
        ctx.fillText(def, 200, 330, 20);
        ctx.fillText(phy, 200, 355, 20);

        ctx.font = "200 26px Arial";
        //left atr
        ctx.fillText("PAC", 120, 305, 30);
        ctx.fillText("SHO", 120, 330, 30);
        ctx.fillText("PAS", 120, 355, 30);

        //right atr
        ctx.fillText("DRI", 230, 305, 30);
        ctx.fillText("DEF", 230, 330, 30);
        ctx.fillText("PHY", 230, 355, 30);
    }
</script>



<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Zawodnik
        </dt>

        <dd>
            @if (Model.Footballer.Alias != " ")
            {
                @Model.Footballer.FirstName
                @:
                @Model.Footballer.LastName
            }
            else
            {
                @Model.Footballer.FirstName
                @:
                @Model.Footballer.LastName
                @: "
                @Model.Footballer.Alias
                @:"
            }
        </dd>

        <dt>
            Średnia cena
        </dt>

        <dd>
            @Model.AvaragePrice
            @if (User.Identity.IsAuthenticated)
            {
                using (Html.BeginForm("AddPrice", "Cards"))
                {
                    <input type="hidden" id="id" name="id" value="@Model.ID" />
                    <input type="number" id="tbPrice" name="tbPrice" value="600" min="1" />
                    <input type="submit" id="addPrice" value="Dodaj cenę zakupu" />
                }
            }
        </dd>

        <dt>
            Ocena graczy
        </dt>

        <dd>
            @Model.AvarageRate
        </dd>
        <dd>
            @if (User.Identity.IsAuthenticated)
            {
                using (Html.BeginForm("AddRate", "Cards"))
                {
                    <input type="hidden" id="id" name="id" value="@Model.ID" />
                    <input type="number" id="tbRate" name="tbRate" value="5" min="1" max="5" />
                    <input type="submit" id="addRate" value="Dodaj ocenę" />
                }
            }

        </dd>


        @if (User.Identity.IsAuthenticated)
        {
            <dt>Posiadane</dt>
            <dd>
                @if (!(bool)ViewBag.IsOwned)
                {
                    using (Html.BeginForm("AddToOwned", "Cards"))
                    {
                        <input type="hidden" id="id" name="id" value="@Model.ID" />
                        <input type="submit" id="addToOwned" value="Dodaj kartę do posiadanych" />
                    }

                }
                else
                {
                    @:Posiadane
                }
            </dd>
        }

        @if (User.Identity.IsAuthenticated)
        {
            <dt>Ulubiona</dt>
            <dd>
                @if (!(bool)ViewBag.IsLiked)
                {
                    using (Html.BeginForm("AddToLiked", "Cards"))
                    {
                        <input type="hidden" id="id" name="id" value="@Model.ID" />
                        <input type="submit" id="addToLiked" value="Dodaj do ulubionych" />
                    }
                }
                else
                {
                    @:Ulubiona
                }
            </dd>

        }

    </dl>
</div>
<div>
    @if (!(bool)ViewBag.IsComment)
    {
        if (User.Identity.IsAuthenticated)
        {
            @: Bądź pierwszy i napisz co myślisz o tej karcie.

            using (Html.BeginForm("AddOpinion", "Cards"))
            {
                <input type="hidden" id="id" name="id" value="@Model.ID" />
                <textarea id="opinion" name="opinion" rows="4" cols="50" placeholder="Twój komentarz..."></textarea>
                <input type="submit" id="addOpinion" value="Dodaj komentarz" />
            }
        }
    }
    else
    {
        if (User.Identity.IsAuthenticated)
        {
            using (Html.BeginForm("AddOpinion", "Cards"))
            {
                <input type="hidden" id="id" name="id" value="@Model.ID" />
                <textarea id="opinion" name="opinion" rows="4" cols="50" placeholder="Twój komentarz..."></textarea>
                <input type="submit" id="addOpinion" value="Dodaj komentarz" />
            }
        }
        <dl>
            @foreach (var item in ViewBag.Comments)
            {
                <dt>
                    @if (item.Profile.Avatar != null)
                    {
                        <img src="~/Images/@item.Profile.Avatar" width="40px" height="40px" />
                    }
                    @item.Profile.Username
                    @item.Time
                </dt>
                <dd>@item.Message</dd>
            }
        </dl>
    }
</div>
<p>
    @if (Context.User.IsInRole("Moderator"))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID })
        @:|
    }
    @Html.ActionLink("Powrót do listy", "Index")
</p>

Views/Cards/Index.cshtml
@model PagedList.IPagedList<FifaStore.Models.Card>
@using PagedList.Mvc;
@using Newtonsoft.Json

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Karty";
}

<h2>Karty</h2>

@if (Context.User.IsInRole("Moderator"))
{
    <p>
        @Html.ActionLink("Dodaj kartę", "Create")
    </p>
}

@using (Html.BeginForm("Index", "Cards", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        @Html.DropDownList("NationSortParm", new SelectList(ViewBag.Nations, "ID", "Name"), "Narodowość")
        @Html.DropDownList("LeagueSortParm", new SelectList(ViewBag.Leagues, "ID", "Name"), "Liga")
        @Html.DropDownList("CardTypeSortParm", new SelectList(ViewBag.CardTypes, "ID", "Name"), "Typ karty")
        @Html.DropDownList("PositionSortParm", new SelectList(ViewBag.Positions), "Pozycja")
        @Html.TextBox("PriceMin", ViewBag.PriceMin as string)
        @Html.TextBox("PriceMax", ViewBag.PriceMax as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Karta
        </th>
        <th>
            @Html.ActionLink("Imię, nazwisko, alias", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter, leagueSortParm = ViewBag.LeagueSortParm, nationSortParm = ViewBag.NationSortParm, cardTypeSortParm = ViewBag.CardTypeSortParm, priceMin = ViewBag.PriceMin, priceMax = ViewBag.PriceMax })
        </th>
        <th>
            @Html.ActionLink("Overall", "Index", new { sortOrder = ViewBag.OverallSortParm, currentFilter = ViewBag.CurrentFilter, leagueSortParm = ViewBag.LeagueSortParm, nationSortParm = ViewBag.NationSortParm, cardTypeSortParm = ViewBag.CardTypeSortParm, priceMin = ViewBag.PriceMin, priceMax = ViewBag.PriceMax })
        </th>
        <th>
            Pozycja
        </th>
        <th>
            @Html.ActionLink("Średnia cena", "Index", new { sortOrder = ViewBag.AvaragePriceSortParm, currentFilter = ViewBag.CurrentFilter, leagueSortParm = ViewBag.LeagueSortParm, nationSortParm = ViewBag.NationSortParm, cardTypeSortParm = ViewBag.CardTypeSortParm, priceMin = ViewBag.PriceMin, priceMax = ViewBag.PriceMax })
        </th>
        <th>
            @Html.ActionLink("Ocena", "Index", new { sortOrder = ViewBag.RateSortParm, currentFilter = ViewBag.CurrentFilter, leagueSortParm = ViewBag.LeagueSortParm, nationSortParm = ViewBag.NationSortParm, cardTypeSortParm = ViewBag.CardTypeSortParm, priceMin = ViewBag.PriceMin, priceMax = ViewBag.PriceMax })
        </th>
        @if (Context.User.IsInRole("Moderator"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="/Cards/Details?id=@item.ID">
                    <img src="~/Images/@item.CardType.CardBorder" alt="@item.CardType.CardBorder" height="50px" width="36px" />
                    <img src="~/Images/@item.Footballer.Photo" alt="@item.Footballer.Photo" height="50px" width="50px" />
                    <img src="~/Images/@item.Footballer.Nationality.Flag" alt="@item.Footballer.Nationality.Flag" height="50px" width="72px" />
                    <img src="~/Images/@item.Footballer.Club.ClubCrest" alt="@item.Footballer.Club.ClubCrest" height="50px" width="50px" />
                </a>
            </td>
            <td>
                @if (item.Footballer.Alias != " ")
                {
                    @item.Footballer.FirstName
                    @:
                    @item.Footballer.LastName
                }
                else
                {
                    @item.Footballer.FirstName
                    @:
                    @item.Footballer.LastName
                    @: "
                    @item.Footballer.Alias
                    @:"
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Overall)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvaragePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvarageRate)
            </td>
            @if (Context.User.IsInRole("Moderator"))
            {
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }
</table>

<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Views/Cards/SquadBuilder.cshtml
@model FifaStore.Models.Card

@{
    ViewBag.Title = "SquadBuilder";
}

<h2>SquadBuilder</h2>